sonar.projectKey=Mahery23_skillhub
sonar.organization=mahery23

# Sources a analyser
sonar.sources=backend/app,frontend/src

# Tests
sonar.tests=backend/tests

# Rapports de coverage
sonar.php.coverage.reportPaths=backend/coverage.xml

# Exclusions de l'analyse (vendor, build, configs, tests dans les sources)
sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**,**/storage/**,**/bootstrap/cache/**,**/*.blade.php,**/public/**

# Exclusions de la coverage (fichiers qu'on n'a pas a couvrir)
sonar.coverage.exclusions=backend/app/Console/**,backend/app/Exceptions/**,backend/app/Providers/**,backend/database/migrations/**,backend/database/seeders/**,frontend/src/main.jsx,frontend/src/App.jsx,frontend/vite.config.js

# Encodage
sonar.sourceEncoding=UTF-8
